### ISSUE TITLE
getMedia() don't work with specific post id 

### ISSUE THREAD

**Issue by hivvu** [estebanmunchjones2019/academind-next.js-tech-blog#1]
Following your tutorial, I've noticed that your GetMedia() function gets only the latest 10 media assets and not the featured media from that specific post. 

Will try to explain, if we have 5 latest posts from a blog, but one of them has 3 images on it's content, this means, that the first 4 images from the endpoint /media/ will be from this post and it will give an error when trying to show to others posts on the homepage.

**Comment by estebanmunchjones2019** [comment]
thanks a lot @hivvu ! I changed the `posts` and `events` call to the WordPress backend, so that now they include the featured media on the same response. Let me know if the issue still persists after the changes I've made.

**Comment by hivvu** [comment]
Thanks @estebanmunchjones2019, that was fast! 
It's working flawlessly now. 😉

**Comment by esilverman682** [comment]
ERROR ON BUILD: When changing the BASE_URL in the wordpress.js file 

1. CONTENT MODELER - made the API public
2. USING WP GRAPHQL

> Build error occurred
TypeError: elements.map is not a function
    at getSlugs (/mywordpress-simple/.next/server/chunks/51.js:52:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getStaticPaths (/mywordpress-simple/.next/server/pages/events/[slug].js:49:17)
    at async buildStaticPaths (/mywordpress-simple/node_modules/next/dist/build/utils.js:16:80)
    at async /mywordpress-simple/node_modules/next/dist/build/utils.js:26:622
    at async Span.traceAsyncFn (/mywordpress-simple/node_modules/next/dist/telemetry/trace/trace.js:6:584) {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
