### ISSUE TITLE
Write to wordpress database 

### ISSUE THREAD

**Issue by sagspot** [estebanmunchjones2019/academind-next.js-tech-blog#2]
The site https://www.sportslink.info/ got me thinking, how do you write data to the WordPress database?

It has the join, give and contact form that accepts data which should then be written to the db. Do you need a plugin to do that?

 If yes what plugin do you recommend?

And can it also be achieved without a plugin? If yes, how?

**Comment by estebanmunchjones2019** [comment]
Hi Oliver,

Thanks for reaching out. I'm not writing data to the WP database. Users
would need to be authenticated in order to do that using the REST API.

You could use this one https://github.com/auth0/wp-auth0

Cheers!

*Esteban Munch Jones*
